services:
  etcd:
    image: bitnami/etcd:3.4.9
    user: root
    restart: always
    volumes:
      - ./docker/etcd_data:/etcd_data
    environment:
      ETCD_DATA_DIR: /etcd_data
      ETCD_ENABLE_V2: "true"
      ALLOW_NONE_AUTHENTICATION: "no"
      ETCD_ROOT_PASSWORD: $ETCD_ROOT_PASSWORD
      ETCD_ADVERTISE_CLIENT_URLS: "http://etcd:2379"
      ETCD_LISTEN_CLIENT_URLS: "http://0.0.0.0:2379"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "etcdctl",
          "endpoint",
          "health",
          "root:$ETCD_ROOT_PASSWORD",
          "--cluster=false",
        ]
      interval: 10s
      timeout: 10s
      retries: 3
    ports:
      - "2379:2379/tcp"
    networks:
      - apisix

  apisix:
    image: apache/apisix:2.13.1-alpine
    restart: always
    environment:
      DOMAIN_NAME: $DOMAIN_NAME
      ETCD_ROOT_PASSWORD: $ETCD_ROOT_PASSWORD
      ADMIN_KEY: $ADMIN_KEY
    ports:
      - "9080:9080"
      - "9443:9443"
    volumes:
      - ./docker/apisix/config.yaml:/usr/local/apisix/conf/config.yaml
      - /etc/letsencrypt:/etc/letsencrypt
    networks:
      - apisix
    depends_on:
      etcd:
        condition: service_healthy

  apisix-dashboard:
    image: apache/apisix-dashboard:3.0.1-alpine
    restart: always
    environment:
      ENABLE_PROXY: false
      ETCD_ROOT_PASSWORD: $ETCD_ROOT_PASSWORD
    ports:
      - 9000:9000
    volumes:
      - ./docker/apisix-dashboard/conf.yaml:/usr/local/apisix-dashboard/conf/conf.yaml
    networks:
      - apisix
    depends_on:
      etcd:
        condition: service_healthy
      apisix:
        condition: service_started

networks:
  apisix:
    driver: bridge
